[CICD] Launch psql djngo service and app + check pods status

diff --git a/.github/workflows/sbt-scala-build.yaml b/.github/workflows/sbt-scala-build.yaml
--- a/.github/workflows/sbt-scala-build.yaml
+++ b/.github/workflows/sbt-scala-build.yaml
@@ -81,7 +81,6 @@ jobs:
           wget https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/models/pos_anc_en_3.0.0_3.0_1614962126490.zip
           unzip pos_anc_en_3.0.0_3.0_1614962126490.zip -d ./jars/pos_anc_en
 
-
       - name : See uploaded artifacts 
         run: ls ./jars
 
@@ -94,6 +93,10 @@ jobs:
       - name: Setup Kafka
         run: |
           kubectl apply -f  kind/k8s_config/kafka
+
+      - name: Setup Django + PSQL
+        run: |
+          kubectl apply -f  kind/k8s_config/django
       - name: Helm install
         run: |
           helm repo add spark-operator https://kubeflow.github.io/spark-operator
@@ -133,3 +136,28 @@ jobs:
               sleep 10
             fi
           done
+
+      - name: Check Django application status
+        run: |
+          while true; do
+            POD_STATUS=$(k get pods --selector=name=django-deploy -o jsonpath='{.items[*].status.phase}')
+            echo $POD_STATUS
+
+            if [ "$POD_STATUS" == "Running" ]; then
+              echo "Django Application Deployed"
+              exit 0
+            elif [ "$POD_STATUS" == "Succeeded" ]; then
+              echo "Django Application Deployed"
+              exit 0
+            elif [ "$POD_STATUS" == "Failed" ]; then
+              echo "Django Application Failed during deployment"
+              exit 1
+            elif [ "$POD_STATUS" == "Unknown" ]; then
+              echo "Django Application Unknow Status"
+              exit 1
+            else
+              echo "Django Application still running, Waiting ..."
+              sleep 10
+            fi
+          done
+
